// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TENANT_MANAGEMENT.Data;

#nullable disable

namespace TENANT_MANAGEMENT.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260317152248_ChoThuePhongTro")]
    partial class ChoThuePhongTro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTHD"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaDV")
                        .HasColumnType("int");

                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaHD");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.ChuTro", b =>
                {
                    b.Property<int>("MaChuTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuTro"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChuTro");

                    b.ToTable("ChuTros");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.DangNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DangNhaps");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<string>("DonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaDV")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TenDV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDV");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("HoadonBusinessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaPhongTro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ThangHoaDon")
                        .HasColumnType("date");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("HoadonBusinessCode")
                        .IsUnique();

                    b.HasIndex("MaPhongTro", "ThangHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("HopdongBusinessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaKhachThue")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongTro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TienThueHangThang")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHopDong");

                    b.HasIndex("HopdongBusinessCode")
                        .IsUnique();

                    b.HasIndex("MaKhachThue");

                    b.HasIndex("MaPhongTro");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.KhachThue", b =>
                {
                    b.Property<int>("MaKhachThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachThue"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhachThue");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.ToTable("KhachThues");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.KhuTro", b =>
                {
                    b.Property<int>("MaKhuTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuTro"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaChuTro")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKhuTro");

                    b.HasIndex("MaChuTro");

                    b.ToTable("KhuTros");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.PhongTro", b =>
                {
                    b.Property<int>("MaPhongTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongTro"));

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaKhuTro")
                        .HasColumnType("int");

                    b.Property<string>("PhongtroBusinessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhongTro");

                    b.HasIndex("MaKhuTro")
                        .IsUnique();

                    b.HasIndex("PhongtroBusinessCode")
                        .IsUnique();

                    b.ToTable("PhongTros");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("TENANT_MANAGEMENT.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TENANT_MANAGEMENT.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.HoaDon", b =>
                {
                    b.HasOne("TENANT_MANAGEMENT.Models.PhongTro", "PhongTro")
                        .WithMany("CacHoaDon")
                        .HasForeignKey("MaPhongTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.HopDong", b =>
                {
                    b.HasOne("TENANT_MANAGEMENT.Models.KhachThue", "KhachThue")
                        .WithMany("HopDong")
                        .HasForeignKey("MaKhachThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TENANT_MANAGEMENT.Models.PhongTro", "PhongTro")
                        .WithMany("CacHopDong")
                        .HasForeignKey("MaPhongTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.KhuTro", b =>
                {
                    b.HasOne("TENANT_MANAGEMENT.Models.ChuTro", "ChuTro")
                        .WithMany("KhuTros")
                        .HasForeignKey("MaChuTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuTro");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.PhongTro", b =>
                {
                    b.HasOne("TENANT_MANAGEMENT.Models.KhuTro", "KhuTro")
                        .WithMany("PhongTros")
                        .HasForeignKey("MaKhuTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuTro");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.ChuTro", b =>
                {
                    b.Navigation("KhuTros");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.KhachThue", b =>
                {
                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.KhuTro", b =>
                {
                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("TENANT_MANAGEMENT.Models.PhongTro", b =>
                {
                    b.Navigation("CacHoaDon");

                    b.Navigation("CacHopDong");
                });
#pragma warning restore 612, 618
        }
    }
}
